### ISSUE TITLE
Script for setup automation

### ISSUE THREAD

**Issue by BolajiOlajide** [gbozee/react-django-admin#10]
I think we should come up with a script that does the initial setup for a new user and all. So all the person needs to run is `./run.sh` and all is well.  

What do you think? @gbozee 

Also is there the possibility of porting this project to the PythonNigeria github page?

**Comment by gbozee** [comment]
The project is still at its infancy and a lot of implementation are still ironed out which is why it is still here. 

Also, a a single startup script file isn't helpful at this stage because one can either choose to work on the frontend or on the backend. They are yet to be coupled in anyway yet. And they both have different setups

**Comment by BolajiOlajide** [comment]
Yes, the project is still in it's infancy, Correct!
But I think having a script that sets it up and can be revised over time ensures one doesn't make mistakes and the process is simply automated.

Maybe I'm thinking about the future, just thought it would be a good idea hence the suggestion.
